language: c++
matrix:
  include:
    - name: "Build AFL"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6
          packages:
            - llvm-6-dev
            - clang-6
      script:
        - export CC=clang
        - export CXX=clang++
        - ./setup.sh