language: c++
matrix:
  include:
    - name: "Build AFL"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
          packages:
            - llvm-6.0-dev
            - clang-6.0
      script:
        - export CC=clang
        - export CXX=clang++
        - ./setup.sh