language: c++
matrix:
  include:
    - name: "Build AFL"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - llvm-5.0-dev
            - gcc-4.8
            - g++-4.8
      script:
        #- mkdir ~/bin
        #- ln -s `which llvm-config-5.0` ~/bin/llvm-config`
        #- ln -s `which clang-5.0` ~/bin/clang`
        #- export PATH=~/bin/:$PATH
        - which clang
        - which clang++
        - which gcc-4.8
        - which g++-4.8
        - which llvm-config
        - llvm-config --cxxflags
        #- echo $PATH | awk 'BEGIN{RS=":"}{print "echo ls "$0" && ls "$0}' | bash
        - export CC=gcc-4.8
        - export CXX=g++-4.8
        - ./setup.sh