language: c++
matrix:
  include:
    - name: "Build AFL"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - llvm-5.0-dev
            - gcc-4.8
            - g++-4.8
      script:
        #- mkdir ~/bin
        #- ln -s `which llvm-config-5.0` ~/bin/llvm-config`
        #- ln -s `which clang-5.0` ~/bin/clang`
        #- export PATH=~/bin/:$PATH
        - echo `which clang`
        - echo `which clang++`
        - echo `which gcc-4.8`
        - echo `which g++-4.8++`
        #- echo $PATH | awk 'BEGIN{RS=":"}{print "echo ls "$0" && ls "$0}' | bash
        - export CC=gcc-4.8
        - export CXX=g++-4.8
        - ./setup.sh